services:
  work:
    build: .
    runtime: nvidia
    stdin_open: true
    tty: true
    ipc: host
    volumes:
      - $PWD/:/workspace
    working_dir: /workspace
    environment:
      - PYTHONPATH=/workspace
      - NVIDIA_VISIBLE_DEVICES=0
    ulimits:
      memlock: -1
      stack: 67108864
